import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Ishwor's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'h-[2000px] ${nunito.className}'}>
      <Header/>
      {children}
      </body>
    </html>
  );
}
